"""create tables

Revision ID: 3fd3f2c83bb2
Revises: 
Create Date: 2026-03-12 02:20:10.324294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd3f2c83bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_name', sa.String(length=100), nullable=False),
    sa.Column('auth_email', sa.String(length=100), nullable=True),
    sa.Column('auth_phone', sa.String(length=20), nullable=False),
    sa.Column('auth_address', sa.String(length=200), nullable=False),
    sa.Column('auth_password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_email'),
    sa.UniqueConstraint('auth_phone')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_name', sa.String(length=100), nullable=False),
    sa.Column('stu_age', sa.DateTime(), nullable=False),
    sa.Column('stu_email', sa.String(length=100), nullable=False),
    sa.Column('stu_password', sa.String(length=100), nullable=False),
    sa.Column('stu_phone', sa.String(length=10), nullable=False),
    sa.Column('stu_address', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stu_email'),
    sa.UniqueConstraint('stu_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('author')
    # ### end Alembic commands ###
